# Fine-tune `abdullahg7/cardd-yolov8s` on VehiDE

In [2]:
!pip install -q ultralytics huggingface_hub

import json, shutil, time
from pathlib import Path

import torch

assert torch.cuda.is_available(), "Enable GPU in Settings → Accelerator before running."
print("GPU:", torch.cuda.get_device_name(0))

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 30.6 MB/s eta 0:00:0000:01
GPU: Tesla T4

## 1. Mount the converted segmentation dataset

In [3]:
!ls /kaggle/input/

SEG_ROOT = Path("/kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset")
SEG_IMAGES_LABELS_ROOT = SEG_ROOT / "vehide_seg"
SEG_DATA_YAML_SOURCE = SEG_ROOT / "damage-seg.yaml"

assert SEG_ROOT.exists(), "Segmentation dataset not found at this path — check /kaggle/input/ above and update SEG_ROOT."
assert SEG_IMAGES_LABELS_ROOT.exists(), f"Expected images/labels under {SEG_IMAGES_LABELS_ROOT}, not found."
assert SEG_DATA_YAML_SOURCE.exists(), f"Expected damage-seg.yaml at {SEG_DATA_YAML_SOURCE}, not found."

print(open(SEG_DATA_YAML_SOURCE).read())

CLASS_NAMES = ["dent", "scratch", "crack", "broken_lamp", "shattered_glass", "flat_tyre"]

datasets
names:
- dent
- scratch
- crack
- broken_lamp
- shattered_glass
- flat_tyre
nc: 6
path: /kaggle/working/vehide_seg
test: images/test
train: images/train
val: images/val

In [4]:
import yaml

with open(SEG_DATA_YAML_SOURCE) as f:
    cfg = yaml.safe_load(f)
cfg["path"] = str(SEG_IMAGES_LABELS_ROOT)

SEG_DATA_YAML = "/kaggle/working/damage-seg.yaml"
with open(SEG_DATA_YAML, "w") as f:
    yaml.safe_dump(cfg, f)
print(open(SEG_DATA_YAML).read())

names:
- dent
- scratch
- crack
- broken_lamp
- shattered_glass
- flat_tyre
nc: 6
path: /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg
test: images/test
train: images/train
val: images/val

## 2. Download the pretrained CarDD checkpoint

In [5]:
from huggingface_hub import hf_hub_download
from ultralytics import YOLO

cardd_weights = hf_hub_download(repo_id="abdullahg7/cardd-yolov8s", filename="v2.0/best.pt")
print("Downloaded:", cardd_weights)

probe = YOLO(cardd_weights)
print("\nPretrained CarDD model's own class list (for reference — not necessarily")
print("the same order as this project's 6 classes; the head is reinitialised below")
print("since we are fine-tuning on our own class set):")
print(probe.names)
print("\nTask:", probe.task)

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

v2.0/best.pt:   0%|          | 0.00/23.9M [00:00<?, ?B/s]

Downloaded: /root/.cache/huggingface/hub/models--abdullahg7--cardd-yolov8s/snapshots/9ee0339097a4c01cc70d5a61bc397c5026032260/v2.0/best.pt

Pretrained CarDD model's own class list (for reference — not necessarily
the same order as this project's 6 classes; the head is reinitialised below
since we are fine-tuning on our own class set):
{0: 'dent', 1: 'scratch', 2: 'crack', 3: 'glass_shatter', 4: 'lamp_broken', 5: 'tire_flat'}

Task: segment

## 3. Fine-tune, with multi-session checkpoint relay

In [6]:
import os
import subprocess
from kaggle_secrets import UserSecretsClient

secrets = UserSecretsClient()
os.environ["KAGGLE_USERNAME"] = secrets.get_secret("KAGGLE_USERNAME")
os.environ["KAGGLE_KEY"] = secrets.get_secret("KAGGLE_KEY")

auth_check = subprocess.run(
    ["kaggle", "datasets", "list", "-s", "zzz_auth_check_zzz", "-p", "1"],
    capture_output=True, text=True,
)
if auth_check.returncode != 0:
    print("STDOUT:", auth_check.stdout)
    print("STDERR:", auth_check.stderr)
    raise RuntimeError(
        "Kaggle API authentication failed. Checkpoint backups will NOT work "
        "until this is fixed. Check:\n"
        "  1. Add-ons -> Secrets -> confirm KAGGLE_USERNAME and KAGGLE_KEY are "
        "both added AND toggled ON for this notebook (Kaggle requires "
        "per-notebook attachment, not just creating the secret once).\n"
        "  2. The values match your actual kaggle.json exactly (re-download a "
        "fresh token from kaggle.com/settings -> API -> Create New Token if unsure).\n"
        "  3. Consider upgrading the kaggle package: !pip install -q -U kaggle"
    )
print("Kaggle API authentication OK.")

RUN_NAME = "cardd_yolov8s_seg_finetune"

SESSION_EPOCH_BUDGET = 999   # effectively "never stop early"
BACKUP_EVERY_N_EPOCHS = 5
BACKUP_SLUG = "cardd-seg-finetune-checkpoint-backup"
BACKUP_DATASET_ID = f"{os.environ['KAGGLE_USERNAME']}/{BACKUP_SLUG}"

BACKUP_STAGE = Path("/kaggle/working/checkpoint_backup_seg")
BACKUP_STAGE.mkdir(parents=True, exist_ok=True)

SEG_TRAIN_ARGS = dict(
    data=SEG_DATA_YAML,
    epochs=40,
    imgsz=1280,
    batch=4,
    optimizer="AdamW",
    lr0=0.0005,
    lrf=0.001,
    cos_lr=True,
    weight_decay=0.0005,
    warmup_epochs=3,
    cls=0.5,
    patience=15,
    seed=42,
    deterministic=True,
    plots=True,
    project="/kaggle/working/runs/cardd_seg",
)
print(json.dumps(SEG_TRAIN_ARGS, indent=2))

Kaggle API authentication OK.
{
  "data": "/kaggle/working/damage-seg.yaml",
  "epochs": 40,
  "imgsz": 1280,
  "batch": 4,
  "optimizer": "AdamW",
  "lr0": 0.0005,
  "lrf": 0.001,
  "cos_lr": true,
  "weight_decay": 0.0005,
  "warmup_epochs": 3,
  "cls": 0.5,
  "patience": 15,
  "seed": 42,
  "deterministic": true,
  "plots": true,
  "project": "/kaggle/working/runs/cardd_seg"
}

In [7]:
meta_check = subprocess.run(
    ["kaggle", "datasets", "metadata", BACKUP_DATASET_ID, "-p", "/tmp/meta_check_seg"],
    capture_output=True, text=True,
)
check = meta_check.returncode
resume_from = None

if check == 0:
    print(f"Found existing backup: {BACKUP_DATASET_ID} — downloading...")
    os.makedirs("/kaggle/working/recovered_seg", exist_ok=True)
    dl = subprocess.run(
        ["kaggle", "datasets", "download", BACKUP_DATASET_ID,
         "-p", "/kaggle/working/recovered_seg", "--unzip", "-q"],
        capture_output=True, text=True,
    )
    if dl.returncode != 0:
        print(dl.stdout, dl.stderr)
        raise RuntimeError("Backup dataset metadata was found, but downloading it failed. "
                          "Check the output above before proceeding.")
    recovered_pt = list(Path("/kaggle/working/recovered_seg").rglob("last.pt"))
    if recovered_pt:
        resume_from = recovered_pt[0]
        epoch_marker = Path("/kaggle/working/recovered_seg/epoch.txt")
        print(f"Will resume from epoch {epoch_marker.read_text().strip() if epoch_marker.exists() else '?'}")
else:
    print(f"No existing backup dataset ({BACKUP_DATASET_ID}) — session 1, "
          f"starting fresh from the CarDD checkpoint.")
    print(f"(kaggle CLI returned: {meta_check.stderr.strip()[:200]})")

Found existing backup: m4rcuseryx/cardd-seg-finetune-checkpoint-backup — downloading...
Will resume from epoch 15

In [8]:
_session_start_epoch = {"value": None}
_dataset_exists = {"value": check == 0}
_backup_failures = []

def _push_backup(trainer, completed_epoch):
    last_pt = trainer.save_dir / "weights" / "last.pt"
    if not last_pt.exists():
        return
    shutil.copy(last_pt, BACKUP_STAGE / "last.pt")
    for extra in ("results.csv", "args.yaml"):
        p = trainer.save_dir / extra
        if p.exists():
            shutil.copy(p, BACKUP_STAGE / extra)
    (BACKUP_STAGE / "epoch.txt").write_text(str(completed_epoch))
    (BACKUP_STAGE / "dataset-metadata.json").write_text(json.dumps({
        "title": "CarDD YOLOv8s-seg fine-tune checkpoint backup",
        "id": BACKUP_DATASET_ID,
        "licenses": [{"name": "CC0-1.0"}],
    }))

    if not _dataset_exists["value"]:
        result = subprocess.run(
            ["kaggle", "datasets", "create", "-p", str(BACKUP_STAGE), "--dir-mode", "zip", "-q"],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            _dataset_exists["value"] = True
    else:
        result = subprocess.run(
            ["kaggle", "datasets", "version", "-p", str(BACKUP_STAGE),
             "-m", f"epoch {completed_epoch}", "--dir-mode", "zip", "-q"],
            capture_output=True, text=True,
        )

    if result.returncode == 0:
        print(f"Backed up checkpoint at epoch {completed_epoch} -> {BACKUP_DATASET_ID}")
    else:
        msg = f"BACKUP FAILED at epoch {completed_epoch}: {result.stderr.strip()[:300]}"
        print(f"\n{'='*70}\n{msg}\n{'='*70}\n")
        _backup_failures.append((completed_epoch, result.stderr.strip()))


def relay_callback(trainer):
    completed = trainer.epoch + 1
    if _session_start_epoch["value"] is None:
        _session_start_epoch["value"] = completed - 1
    epochs_this_session = completed - _session_start_epoch["value"]
    is_budget_stop = epochs_this_session >= SESSION_EPOCH_BUDGET
    is_periodic_backup = completed % BACKUP_EVERY_N_EPOCHS == 0

    if is_budget_stop or is_periodic_backup:
        _push_backup(trainer, completed)
    if is_budget_stop:
        print(f"\nSession budget of {SESSION_EPOCH_BUDGET} epochs reached "
              f"(total completed: {completed}/{trainer.epochs}). Stopping gracefully.")
        trainer.stop = True


t0 = time.time()
if resume_from is not None:
    model_seg = YOLO(str(resume_from))
    model_seg.add_callback("on_train_epoch_end", relay_callback)
    results_seg = model_seg.train(resume=True)
else:
    model_seg = YOLO(cardd_weights)
    model_seg.add_callback("on_train_epoch_end", relay_callback)
    results_seg = model_seg.train(name=RUN_NAME, **SEG_TRAIN_ARGS)
wall = time.time() - t0
print(f"\nThis session: {wall/60:.1f} min")

if _backup_failures:
    print(f"\nWARNING: {len(_backup_failures)} backup attempt(s) failed this session. "
          f"If the session dies before you fix this, progress since the last "
          f"SUCCESSFUL backup will be lost. Failed epochs: "
          f"{[e for e, _ in _backup_failures]}")
else:
    print("\nAll backup attempts this session succeeded.")

Ultralytics 8.4.108 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/kaggle/working/damage-seg.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1280, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0005, lrf=0.001, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/recovered_seg/last.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=cardd_yolov8s_seg_finetune-2, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=15, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/runs/cardd_seg, quantize=None, rect=False, resume=/kaggle/working/recovered_seg/last.pt, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 20.8MB/s 0.0s

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2772866  ultralytics.nn.modules.head.Segment          [6, 32, 128, 16, None, [128, 256, 512]]
YOLOv8s-seg summary: 152 layers, 11,792,418 parameters, 11,792,402 gradients, 40.2 GFLOPs

Transferred 417/417 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 84.5MB/s 0.1s
AMP: checks passed ✅
WARNING ⚠️ train: Slow image access detected (ping: 0.9±0.8 ms, read: 20.9±16.0 MB/s, size: 309.0 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels/train... 9545 images, 692 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 9545/9545 267.9it/s 35.6s0.1ss
WARNING ⚠️ train: Cache directory /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels is not writable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 19.5±17.3 MB/s, size: 255.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels/val... 2047 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2047/2047 275.3it/s 7.4s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels is not writable, cache not saved.
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias(decay=0.0)
Plotting labels to /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2/labels.jpg...
Resuming training /kaggle/working/recovered_seg/last.pt from epoch 15 to 30 total epochs
Image sizes 1280 train, 1280 val
Using 2 dataloader workers
Logging results to /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      15/30      4.68G      1.434      2.836      2.293       1.69          0          2       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:240.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 2.9it/s 1:280.3sss
                   all       2047       5042      0.423      0.365      0.345      0.161      0.406      0.343      0.316      0.137

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      16/30      5.81G       1.41      2.789       2.24      1.666          0          3       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:340.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:250.3sss
                   all       2047       5042      0.408      0.382      0.349      0.163      0.394      0.351      0.314      0.137

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      17/30      5.81G       1.38      2.732      2.201      1.647          0          8       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:360.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:260.3sss
                   all       2047       5042      0.419      0.387      0.348      0.167      0.403      0.351      0.313      0.139

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      18/30      5.82G      1.373      2.697      2.165      1.642          0          4       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:370.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:260.3sss
                   all       2047       5042      0.428      0.374      0.354      0.169      0.427      0.347      0.321      0.142

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      19/30      5.82G      1.348       2.66      2.112      1.619          0          8       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:360.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:260.3sss
                   all       2047       5042      0.455       0.37       0.36      0.177      0.434      0.352      0.328      0.149

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      20/30      5.82G      1.332      2.627      2.082      1.605          0          1       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:370.7ss
Backed up checkpoint at epoch 20 -> m4rcuseryx/cardd-seg-finetune-checkpoint-backup
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:250.3sss
                   all       2047       5042      0.456      0.392      0.374       0.18      0.423      0.363      0.334       0.15
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      21/30      5.82G      1.591      2.613      2.197      1.762          0          1       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:230.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:250.3sss
                   all       2047       5042      0.463      0.401      0.376      0.184      0.445      0.373      0.335      0.153

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      22/30      5.82G      1.569      2.566      2.136      1.733          0          0       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:220.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:250.3sss
                   all       2047       5042      0.466      0.395      0.385      0.188      0.474       0.36      0.346      0.159

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      23/30      5.82G      1.557      2.539      2.105      1.723          0          1       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:200.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:240.3sss
                   all       2047       5042      0.475      0.388       0.38      0.189      0.471      0.353       0.34      0.156

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      24/30      5.82G      1.529      2.499      2.056      1.702          0          3       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:190.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:240.3sss
                   all       2047       5042      0.473      0.406      0.389       0.19      0.458      0.386      0.356       0.16

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      25/30      5.82G      1.526      2.473      2.045      1.695          0          2       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:190.2ss
Backed up checkpoint at epoch 25 -> m4rcuseryx/cardd-seg-finetune-checkpoint-backup
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:230.3sss
                   all       2047       5042      0.477      0.404      0.391      0.195      0.467      0.378      0.357      0.163

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      26/30      5.82G       1.51       2.46      2.011      1.687          0          2       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:170.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:230.3sss
                   all       2047       5042       0.48      0.403      0.391      0.195       0.47      0.373      0.354      0.164

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      27/30      5.82G      1.502       2.44      1.986      1.685          0          0       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:210.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:230.3sss
                   all       2047       5042      0.478      0.406      0.394      0.196      0.467      0.385      0.359      0.164

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      28/30      5.82G      1.491      2.424      1.968      1.669          0          1       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:170.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:230.3sss
                   all       2047       5042      0.475       0.41      0.393      0.197      0.462      0.386      0.358      0.164

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      29/30      5.82G        1.5      2.432      1.972      1.671          0          2       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:170.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:230.3sss
                   all       2047       5042      0.484      0.405      0.394      0.196      0.472       0.38      0.359      0.164

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      30/30      5.82G        1.5      2.424      1.971      1.674          0          6       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:190.2ss
Backed up checkpoint at epoch 30 -> m4rcuseryx/cardd-seg-finetune-checkpoint-backup
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:240.3sss
                   all       2047       5042      0.478      0.411      0.395      0.197       0.47      0.386       0.36      0.165

16 epochs completed in 4.229 hours.
Optimizer stripped from /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2/weights/last.pt, 24.0MB
Optimizer stripped from /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2/weights/best.pt, 24.0MB

Validating /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2/weights/best.pt...
Ultralytics 8.4.108 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
YOLOv8s-seg summary (fused): 86 layers, 11,781,922 parameters, 0 gradients, 39.9 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.2it/s 1:190.3sss
                   all       2047       5042       0.48      0.411      0.395      0.197      0.469      0.388       0.36      0.165
                  dent        659        846       0.45      0.235      0.227     0.0955      0.439       0.22      0.208     0.0811
               scratch       1029       2212      0.419      0.285      0.269      0.131      0.392       0.25      0.217     0.0766
                 crack        608        856      0.365      0.249      0.222      0.106       0.36      0.232      0.208     0.0772
           broken_lamp        351        412      0.543      0.476      0.457      0.221      0.509      0.427      0.378      0.156
       shattered_glass        305        321      0.625       0.76      0.746      0.385      0.614      0.738      0.696      0.376
             flat_tyre        304        395       0.48      0.458      0.448      0.243      0.498      0.461      0.454      0.221
Speed: 0.8ms preprocess, 26.2ms inference, 0.0ms loss, 5.1ms postprocess per image
Results saved to /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2

This session: 257.2 min

All backup attempts this session succeeded.

## 4. Evaluate

In [9]:
m = model_seg.val(data=SEG_DATA_YAML, split="test", imgsz=1280)
print("Box    mAP50:", float(m.box.map50), " mAP50-95:", float(m.box.map))
print("Mask   mAP50:", float(m.seg.map50), " mAP50-95:", float(m.seg.map))

import pandas as pd
rows = []
for idx, ci in enumerate(m.box.ap_class_index):
    rows.append({
        "class": CLASS_NAMES[int(ci)],
        "box_mAP50": float(m.box.ap50[idx]),
        "mask_mAP50": float(m.seg.ap50[idx]),
    })
pd.DataFrame(rows).sort_values("mask_mAP50", ascending=False)

Ultralytics 8.4.108 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
YOLOv8s-seg summary (fused): 86 layers, 11,781,922 parameters, 0 gradients, 39.9 GFLOPs
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 10.1±7.1 MB/s, size: 249.1 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels/test... 2047 images, 140 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2047/2047 180.0it/s 11.4s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 128/128 1.2s/it 2:291.1ss
                   all       2047       4846      0.466      0.402      0.378      0.197      0.466      0.371      0.348      0.166
                  dent        648        825      0.436      0.238      0.234     0.0975      0.455      0.219      0.226     0.0872
               scratch       1007       2174      0.404      0.272      0.263      0.126      0.386      0.231      0.202     0.0707
                 crack        537        765      0.353       0.26       0.21     0.0981      0.362      0.237      0.198     0.0669
           broken_lamp        346        392      0.462      0.459      0.405      0.197      0.412      0.372      0.318      0.132
       shattered_glass        309        325       0.61       0.72      0.702      0.388      0.614      0.692      0.675       0.37
             flat_tyre        292        365      0.534      0.466      0.451      0.276      0.567      0.474      0.471      0.268
Speed: 3.7ms preprocess, 59.6ms inference, 0.0ms loss, 4.0ms postprocess per image
Results saved to /kaggle/working/runs/segment/val
Box    mAP50: 0.37774277590480015  mAP50-95: 0.19694032763712255
Mask   mAP50: 0.34834581002467563  mAP50-95: 0.16574885177171825

             class  box_mAP50  mask_mAP50
4  shattered_glass   0.702031    0.675127
5        flat_tyre   0.451360    0.470781
3      broken_lamp   0.405097    0.317771
0             dent   0.234416    0.226248
1          scratch   0.263079    0.202366
2            crack   0.210474    0.197781

## Continuation

In [11]:
CONTINUE_RUN_NAME = "cardd_yolov8s_seg_continued"

CONTINUE_SESSION_EPOCH_BUDGET = 999
CONTINUE_BACKUP_EVERY_N_EPOCHS = 5
CONTINUE_BACKUP_SLUG = "cardd-seg-continuation-checkpoint-backup"
CONTINUE_BACKUP_DATASET_ID = f"{os.environ['KAGGLE_USERNAME']}/{CONTINUE_BACKUP_SLUG}"

CONTINUE_BACKUP_STAGE = Path("/kaggle/working/checkpoint_backup_seg_continue")
CONTINUE_BACKUP_STAGE.mkdir(parents=True, exist_ok=True)

BEST_PT_FROM_ORIGINAL_RUN = "/kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2/weights/best.pt"

CONTINUE_ARGS = dict(
    data=SEG_DATA_YAML,
    epochs=20,
    imgsz=1280,
    batch=4,
    optimizer="AdamW",
    lr0=0.0002,          
    lrf=0.001,
    cos_lr=True,
    weight_decay=0.0005,
    warmup_epochs=1, 
    cls=0.5,
    patience=10,
    close_mosaic=5,
    copy_paste=0.3,
    hsv_v=0.5,
    hsv_s=0.8,
    degrees=10.0,
    shear=5.0,
    scale=0.6,
    seed=42,
    deterministic=True,
    plots=True,
    project="/kaggle/working/runs/cardd_seg",
)
print(json.dumps(CONTINUE_ARGS, indent=2))

{
  "data": "/kaggle/working/damage-seg.yaml",
  "epochs": 20,
  "imgsz": 1280,
  "batch": 4,
  "optimizer": "AdamW",
  "lr0": 0.0002,
  "lrf": 0.001,
  "cos_lr": true,
  "weight_decay": 0.0005,
  "warmup_epochs": 1,
  "cls": 0.5,
  "patience": 10,
  "close_mosaic": 5,
  "copy_paste": 0.3,
  "hsv_v": 0.5,
  "hsv_s": 0.8,
  "degrees": 10.0,
  "shear": 5.0,
  "scale": 0.6,
  "seed": 42,
  "deterministic": true,
  "plots": true,
  "project": "/kaggle/working/runs/cardd_seg"
}

In [12]:
continue_meta_check = subprocess.run(
    ["kaggle", "datasets", "metadata", CONTINUE_BACKUP_DATASET_ID, "-p", "/tmp/meta_check_continue"],
    capture_output=True, text=True,
)
continue_check = continue_meta_check.returncode
continue_resume_from = None

if continue_check == 0:
    print(f"Found existing continuation backup: {CONTINUE_BACKUP_DATASET_ID} — downloading...")
    os.makedirs("/kaggle/working/recovered_continue", exist_ok=True)
    dl = subprocess.run(
        ["kaggle", "datasets", "download", CONTINUE_BACKUP_DATASET_ID,
         "-p", "/kaggle/working/recovered_continue", "--unzip", "-q"],
        capture_output=True, text=True,
    )
    if dl.returncode != 0:
        print(dl.stdout, dl.stderr)
        raise RuntimeError("Continuation backup metadata was found, but downloading it failed.")
    recovered_pt = list(Path("/kaggle/working/recovered_continue").rglob("last.pt"))
    if recovered_pt:
        continue_resume_from = recovered_pt[0]
        epoch_marker = Path("/kaggle/working/recovered_continue/epoch.txt")
        print(f"Will resume the CONTINUATION run from epoch "
              f"{epoch_marker.read_text().strip() if epoch_marker.exists() else '?'}")
else:
    print(f"No existing continuation backup — this is the first session of the "
          f"continuation phase. Starting fresh from {BEST_PT_FROM_ORIGINAL_RUN}")
    print(f"(kaggle CLI returned: {continue_meta_check.stderr.strip()[:200]})")

No existing continuation backup — this is the first session of the continuation phase. Starting fresh from /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2/weights/best.pt
(kaggle CLI returned: )

In [14]:
_continue_session_start_epoch = {"value": None}
_continue_dataset_exists = {"value": continue_check == 0}
_continue_backup_failures = []


def _push_continue_backup(trainer, completed_epoch):
    last_pt = trainer.save_dir / "weights" / "last.pt"
    if not last_pt.exists():
        return
    shutil.copy(last_pt, CONTINUE_BACKUP_STAGE / "last.pt")
    for extra in ("results.csv", "args.yaml"):
        p = trainer.save_dir / extra
        if p.exists():
            shutil.copy(p, CONTINUE_BACKUP_STAGE / extra)
    (CONTINUE_BACKUP_STAGE / "epoch.txt").write_text(str(completed_epoch))
    (CONTINUE_BACKUP_STAGE / "dataset-metadata.json").write_text(json.dumps({
        "title": "CarDD YOLOv8s-seg continuation checkpoint backup",
        "id": CONTINUE_BACKUP_DATASET_ID,
        "licenses": [{"name": "CC0-1.0"}],
    }))

    if not _continue_dataset_exists["value"]:
        result = subprocess.run(
            ["kaggle", "datasets", "create", "-p", str(CONTINUE_BACKUP_STAGE), "--dir-mode", "zip", "-q"],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            _continue_dataset_exists["value"] = True
    else:
        result = subprocess.run(
            ["kaggle", "datasets", "version", "-p", str(CONTINUE_BACKUP_STAGE),
             "-m", f"epoch {completed_epoch}", "--dir-mode", "zip", "-q"],
            capture_output=True, text=True,
        )

    if result.returncode == 0:
        print(f"Backed up continuation checkpoint at epoch {completed_epoch} -> {CONTINUE_BACKUP_DATASET_ID}")
    else:
        msg = f"BACKUP FAILED at epoch {completed_epoch}: {result.stderr.strip()[:300]}"
        print(f"\n{'='*70}\n{msg}\n{'='*70}\n")
        _continue_backup_failures.append((completed_epoch, result.stderr.strip()))


def continue_relay_callback(trainer):
    completed = trainer.epoch + 1
    if _continue_session_start_epoch["value"] is None:
        _continue_session_start_epoch["value"] = completed - 1
    epochs_this_session = completed - _continue_session_start_epoch["value"]
    is_budget_stop = epochs_this_session >= CONTINUE_SESSION_EPOCH_BUDGET
    is_periodic_backup = completed % CONTINUE_BACKUP_EVERY_N_EPOCHS == 0

    if is_budget_stop or is_periodic_backup:
        _push_continue_backup(trainer, completed)
    if is_budget_stop:
        print(f"\nContinuation session budget reached (total completed: "
              f"{completed}/{trainer.epochs}). Stopping gracefully.")
        trainer.stop = True


t0 = time.time()
if continue_resume_from is not None:
    model_continued = YOLO(str(continue_resume_from))
    model_continued.add_callback("on_train_epoch_end", continue_relay_callback)
    results_continued = model_continued.train(resume=True)
else:
    model_continued = YOLO(BEST_PT_FROM_ORIGINAL_RUN)
    model_continued.add_callback("on_train_epoch_end", continue_relay_callback)
    results_continued = model_continued.train(name=CONTINUE_RUN_NAME, **CONTINUE_ARGS)
wall = time.time() - t0
print(f"\nThis session: {wall/60:.1f} min")

if _continue_backup_failures:
    print(f"\nWARNING: {len(_continue_backup_failures)} backup attempt(s) failed. "
          f"Failed epochs: {[e for e, _ in _continue_backup_failures]}")
else:
    print("\nAll backup attempts this session succeeded.")

Ultralytics 8.4.108 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=5, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.3, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/kaggle/working/damage-seg.yaml, degrees=10.0, deterministic=True, device=, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.8, hsv_v=0.5, imgsz=1280, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0002, lrf=0.001, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_finetune-2/weights/best.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=cardd_yolov8s_seg_continued, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/runs/cardd_seg, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_continued, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.6, seed=42, shear=5.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=1, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2772866  ultralytics.nn.modules.head.Segment          [6, 32, 128, 16, None, [128, 256, 512]]
YOLOv8s-seg summary: 152 layers, 11,792,418 parameters, 11,792,402 gradients, 40.2 GFLOPs

Transferred 417/417 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 404.0±149.8 MB/s, size: 320.6 KB)
train: Scanning /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels/train... 9545 images, 692 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 9545/9545 759.8it/s 12.6s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels is not writable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 280.6±61.8 MB/s, size: 229.3 KB)
val: Scanning /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels/val... 2047 images, 139 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2047/2047 756.4it/s 2.7s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels is not writable, cache not saved.
optimizer: AdamW(lr=0.0002, momentum=0.937) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias(decay=0.0)
Plotting labels to /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_continued/labels.jpg...
Image sizes 1280 train, 1280 val
Using 2 dataloader workers
Logging results to /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_continued
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       1/20      12.5G      1.387      2.719      2.261      1.623          0          2       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.6it/s 15:130.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:250.3sss
                   all       2047       5042       0.44      0.387      0.355      0.169      0.427      0.359      0.325      0.145

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       2/20      4.91G      1.315      2.539      2.091      1.568          0          6       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 15:000.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 2.9it/s 1:290.3sss
                   all       2047       5042      0.436       0.38      0.354       0.17      0.417      0.353      0.317      0.144

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       3/20      4.91G      1.291      2.476      2.037      1.554          0          9       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.6it/s 15:080.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:260.3sss
                   all       2047       5042      0.431      0.375      0.354      0.171      0.435      0.348      0.322      0.145

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       4/20      4.91G       1.29      2.461      2.022      1.548          0          4       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.6it/s 15:050.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:250.3sss
                   all       2047       5042      0.438      0.374      0.357      0.171      0.436      0.342      0.319      0.146

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       5/20      5.01G       1.27      2.436      1.987      1.531          0         12       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:570.2ss
Backed up continuation checkpoint at epoch 5 -> m4rcuseryx/cardd-seg-continuation-checkpoint-backup
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:260.3sss
                   all       2047       5042      0.454      0.382      0.357      0.172      0.446      0.365      0.334       0.15

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       6/20      5.01G      1.263      2.419      1.973      1.525          0          1       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:580.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:230.3sss
                   all       2047       5042      0.449      0.387      0.367      0.173      0.424      0.357      0.326      0.146

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       7/20      5.01G      1.282      2.442      2.006      1.542          0          1       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:580.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:260.3sss
                   all       2047       5042      0.434      0.398      0.361      0.174       0.41      0.373      0.325      0.148

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       8/20      5.01G      1.261      2.411      1.955      1.517          0          2       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:580.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:250.3sss
                   all       2047       5042      0.459      0.381      0.366       0.18      0.458       0.36      0.338      0.155

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       9/20      5.01G       1.26        2.4      1.944      1.514          0          4       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:580.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:250.3sss
                   all       2047       5042      0.462      0.381      0.377      0.182      0.457      0.352      0.339      0.155

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      10/20      5.01G      1.239      2.376      1.917      1.503          0          2       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:600.2ss
Backed up continuation checkpoint at epoch 10 -> m4rcuseryx/cardd-seg-continuation-checkpoint-backup
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:260.3sss
                   all       2047       5042      0.453      0.394      0.372      0.179      0.439      0.371      0.338      0.153

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      11/20      5.01G      1.234      2.359      1.895      1.501          0          9       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 15:000.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:240.3sss
                   all       2047       5042      0.435      0.417      0.384      0.189      0.417      0.385      0.348       0.16

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      12/20      5.01G      1.223      2.324      1.868       1.49          0          0       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:590.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:240.3sss
                   all       2047       5042      0.472        0.4      0.384      0.189      0.458      0.374      0.351      0.161

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      13/20      5.01G      1.221      2.319      1.864      1.491          0          8       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:590.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:240.3sss
                   all       2047       5042      0.462      0.403       0.38      0.188      0.447      0.382      0.348      0.158

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      14/20      5.09G      1.211      2.312      1.834      1.478          0          2       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 15:000.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:240.3sss
                   all       2047       5042      0.473      0.399      0.387      0.194       0.48       0.37      0.355      0.164

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      15/20      5.09G      1.211      2.311      1.836      1.486          0          6       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.7it/s 14:580.2ss
Backed up continuation checkpoint at epoch 15 -> m4rcuseryx/cardd-seg-continuation-checkpoint-backup
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.0it/s 1:240.3sss
                   all       2047       5042      0.483      0.399      0.391      0.193      0.466      0.374      0.356      0.163
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      16/20      5.09G      1.567      2.489       2.04      1.711          0          6       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:210.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:230.3sss
                   all       2047       5042      0.471      0.405      0.391      0.195      0.483      0.372       0.36      0.164

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      17/20      5.09G      1.537      2.453      1.997      1.691          0          4       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:190.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:240.3sss
                   all       2047       5042      0.469      0.407      0.392      0.197      0.463      0.387      0.361      0.167

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      18/20      5.09G      1.534      2.444      1.989      1.685          0          1       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:180.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:220.3sss
                   all       2047       5042      0.455      0.415      0.391      0.197      0.459       0.38      0.359      0.167

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      19/20      5.09G      1.536      2.444      1.987      1.679          0          1       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:190.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:220.3sss
                   all       2047       5042      0.453      0.419      0.394      0.197      0.452      0.391      0.361      0.168

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      20/20      5.09G      1.533      2.437      1.993      1.689          0          9       1280: 100% ━━━━━━━━━━━━ 2387/2387 2.8it/s 14:170.2ss
Backed up continuation checkpoint at epoch 20 -> m4rcuseryx/cardd-seg-continuation-checkpoint-backup
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.1it/s 1:220.3sss
                   all       2047       5042      0.454      0.419      0.395      0.198      0.449      0.393      0.362      0.169

20 epochs completed in 5.432 hours.
Optimizer stripped from /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_continued/weights/last.pt, 24.0MB
Optimizer stripped from /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_continued/weights/best.pt, 24.0MB

Validating /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_continued/weights/best.pt...
Ultralytics 8.4.108 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
YOLOv8s-seg summary (fused): 86 layers, 11,781,922 parameters, 0 gradients, 39.9 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 256/256 3.3it/s 1:180.3sss
                   all       2047       5042      0.453      0.422      0.395      0.197      0.449      0.392      0.362      0.168
                  dent        659        846      0.374      0.249       0.23     0.0978      0.395      0.236      0.213      0.083
               scratch       1029       2212      0.387      0.301       0.27      0.131      0.368      0.258      0.218     0.0773
                 crack        608        856      0.377      0.276      0.248      0.119      0.368      0.249      0.225      0.086
           broken_lamp        351        412        0.5      0.485      0.454       0.22      0.487      0.434      0.391      0.167
       shattered_glass        305        321      0.614      0.749      0.708      0.365      0.595       0.71      0.668      0.365
             flat_tyre        304        395      0.464      0.471      0.457      0.251      0.482      0.463      0.457      0.232
Speed: 0.8ms preprocess, 26.2ms inference, 0.0ms loss, 4.7ms postprocess per image
Results saved to /kaggle/working/runs/cardd_seg/cardd_yolov8s_seg_continued

This session: 328.4 min

All backup attempts this session succeeded.

In [16]:
m2 = model_continued.val(data=SEG_DATA_YAML, split="test", imgsz=1280)
print("Box    mAP50:", float(m2.box.map50), " mAP50-95:", float(m2.box.map))
print("Mask   mAP50:", float(m2.seg.map50), " mAP50-95:", float(m2.seg.map))
 
import pandas as pd
rows = []
for idx, ci in enumerate(m2.box.ap_class_index):
    rows.append({
        "class": CLASS_NAMES[int(ci)],
        "box_mAP50": float(m2.box.ap50[idx]),
        "mask_mAP50": float(m2.seg.ap50[idx]),
    })
pd.DataFrame(rows).sort_values("mask_mAP50", ascending=False)

Ultralytics 8.4.108 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.1±0.2 ms, read: 327.4±185.4 MB/s, size: 277.0 KB)
val: Scanning /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels/test... 2047 images, 140 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2047/2047 990.5it/s 2.1s.1ss
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/m4rcuseryx/vehide-segmentation-dataset/vehide_seg/labels is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 128/128 1.2s/it 2:291.1ss
                   all       2047       4846      0.457      0.414      0.388      0.201      0.458      0.386      0.353      0.169
                  dent        648        825      0.416      0.264      0.239     0.0981      0.435      0.244      0.229     0.0873
               scratch       1007       2174      0.385      0.276      0.258      0.125      0.368      0.233      0.203     0.0713
                 crack        537        765      0.358      0.263      0.225       0.11      0.365      0.241      0.209     0.0765
           broken_lamp        346        392      0.466      0.462      0.431      0.204      0.427      0.398      0.335      0.146
       shattered_glass        309        325      0.604      0.723      0.693      0.377      0.604      0.702      0.661      0.359
             flat_tyre        292        365      0.513      0.499      0.483      0.293      0.547      0.496      0.483      0.272
Speed: 3.6ms preprocess, 59.7ms inference, 0.0ms loss, 3.9ms postprocess per image
Results saved to /kaggle/working/runs/segment/val-3
Box    mAP50: 0.3882121332775978  mAP50-95: 0.20116500302634127
Mask   mAP50: 0.35341089656991526  mAP50-95: 0.16874164404315312

             class  box_mAP50  mask_mAP50
4  shattered_glass   0.692946    0.660696
5        flat_tyre   0.483057    0.482821
3      broken_lamp   0.430682    0.335354
0             dent   0.239109    0.229030
2            crack   0.225331    0.209153
1          scratch   0.258147    0.203411